version: "3.7"

services:
  resource-database:
    image: postgres:latest
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./resource-database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      backend:
        aliases:
          - "resource-database"

  song-database:
    image: postgres:latest
    ports:
      - "65433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./song-database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      backend:
        aliases:
          - "song-database"

  resource-service:
    image: evigilans/resource-service:1.0.0
    depends_on:
      resource-database:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  song-service:
    image: evigilans/song-service:1.0.0
    depends_on:
      song-database:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: bridge
