version: "3.7"

services:
  resource-database:
    image: postgres:latest
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./resource-database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      backend:
        aliases:
          - "resource-database"

  song-database:
    image: postgres:latest
    ports:
      - "65433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./song-database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      backend:
        aliases:
          - "song-database"

  resource-service:
    image: evigilans/resource-service:1.0.0
    depends_on:
      resource-database:
        condition: service_started
      eureka-server:
        condition: service_started
      song-service:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      RESOURCE_DB_URL: ${RESOURCE_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
      BS_CONNECTION_STRING: ${BS_CONNECTION_STRING}
    networks:
      - backend

  song-service:
    image: evigilans/song-service:1.0.0
    depends_on:
      song-database:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SONG_DB_URL: ${SONG_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
    networks:
      - backend

  resource-processor:
    image: evigilans/resource-processor:1.0.0
    depends_on:
      eureka-server:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      EUREKA_URL: ${EUREKA_URL}
    networks:
      - backend

  eureka-server:
    image: evigilans/eureka-server:1.0.0
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
    driver: bridge
