server:
  port: 8081

spring:
  application:
    name: resource-service
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  datasource:
    url: jdbc:postgresql://resource-database:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
